#!/bin/bash

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# THIS SCRIPT REQUIRES JQ: apt install jq
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# LuaDNS Details - Replace these Values!
USER_EMAIL="string"
API_TOKEN="string"
ZONE_ID=int
RECORD_ID=int

echo "LuaDNS update starting at $(date '+%Y-%m-%d %H:%M:%S')"

# LuaDNS API URL
API_URL="https://api.luadns.com/v1/zones/$ZONE_ID/records/$RECORD_ID"

# Get the current public IP address
CURRENT_IP=$(curl -s https://ipinfo.io/ip)

# Check if IP retrieval was successful
if [ -z "$CURRENT_IP" ]; then
  echo "Failed to retrieve the current IP address."
  echo
  exit 1
fi

# Get the current record details
RECORD_DETAILS=$(curl -u "$USER_EMAIL":"$API_TOKEN" -H 'Accept: application/json' "$API_URL" -s)
echo $RECORD_DETAILS

# Check if fetching record details was successful
if [ -z "$RECORD_DETAILS" ]; then
  echo "Failed to fetch record details."
  echo
  exit 1
fi

# Extract fields from the record details
RECORD_IP=$(echo "$RECORD_DETAILS" | jq -r '.content')
ZONE_ID=$(echo "$RECORD_DETAILS" | jq -r '.zone_id')
RECORD_ID=$(echo "$RECORD_DETAILS" | jq -r '.id')
RECORD_NAME=$(echo "$RECORD_DETAILS" | jq -r '.name')
RECORD_TYPE=$(echo "$RECORD_DETAILS" | jq -r '.type')
RECORD_TTL=$(echo "$RECORD_DETAILS" | jq -r '.ttl')

# Check if the current IP matches the record IP
if [ "$CURRENT_IP" == "$RECORD_IP" ]; then
  echo "DNS record '$RECORD_NAME' is already up to date with IP: $CURRENT_IP"
  echo
  exit 0
fi

# Create JSON data for the update request
DATA="{\"zone_id\":$ZONE_ID,\"id\":$RECORD_ID,\"name\":\"$RECORD_NAME\",\"type\":\"$RECORD_TYPE\",\"content\":\"$CURRENT_IP\",\"ttl\":$RECORD_TTL}"

# Send a PUT request to update the DNS record
UPDATE_RESPONSE=$(curl -u "$USER_EMAIL":"$API_TOKEN" -H  'Accept: application/json' -X PUT -d "$DATA" "$API_URL" -s)
echo $UPDATE_RESPONSE

# Extract the content field from the update response
UPDATED_CONTENT=$(echo "$UPDATE_RESPONSE" | jq -r '.content')

if [ "$UPDATED_CONTENT" == "$CURRENT_IP" ]; then
  echo "DNS record '$RECORD_NAME' updated successfully with IP: $CURRENT_IP"
  echo
  exit 0
else
  echo "Failed to update DNS record '$RECORD_NAME'. LUA API Error: $UPDATE_RESPONSE"
  echo
  exit 1
fi


# Partially generated by ChatGPT.
